# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_hobby_organization_study_work'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='organization',
        ),
        migrations.AddField(
            model_name='work',
            name='organization',
            field=models.ManyToManyField(to='mainapp.Organization', verbose_name='Организация'),
        ),
    ]
