# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 17:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20161216_2049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='organization',
        ),
        migrations.AddField(
            model_name='work',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Organization', verbose_name='Организация'),
        ),
    ]
