# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20161216_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='site',
            field=models.URLField(blank=True, db_index=True, verbose_name='Сайт'),
        ),
        migrations.AlterField(
            model_name='study',
            name='date_end',
            field=models.DateField(blank=True, verbose_name='Дата окончания обучения'),
        ),
    ]
