# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 18:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20161216_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='date_new',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Новая дата'),
            preserve_default=False,
        ),
    ]
