# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_study_date_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='date_new1',
            field=models.DateField(null=True),
        ),
    ]
