# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_study_date_new1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='study',
            name='date_new',
        ),
        migrations.RemoveField(
            model_name='study',
            name='date_new1',
        ),
        migrations.AlterField(
            model_name='study',
            name='date_end',
            field=models.DateField(verbose_name='Дата окончания обучения'),
        ),
    ]
