# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_auto_20161216_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='flag',
            field=models.BooleanField(default=False, verbose_name='Флаг'),
        ),
    ]
