# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-23 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='link',
            field=models.TextField(default='default_link', verbose_name='Ссылка'),
            preserve_default=False,
        ),
    ]
