# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-23 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20170123_1326'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Наименование')),
                ('period', models.CharField(max_length=32, verbose_name='Период обучения')),
                ('spec', models.CharField(blank=True, max_length=32, verbose_name='Специальность')),
                ('link', models.CharField(blank=True, max_length=64, verbose_name='Ссылка')),
            ],
        ),
        migrations.AlterField(
            model_name='work',
            name='period',
            field=models.CharField(max_length=32, verbose_name='Период работы работы'),
        ),
    ]
