# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-24 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_hobby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hobby',
            name='img',
            field=models.ImageField(upload_to='img/', verbose_name='Иконка'),
        ),
    ]
