# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-27 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_auto_20170125_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='address',
            field=models.CharField(default=None, max_length=128, verbose_name='Адрес'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='phone',
            field=models.CharField(default='N/a', max_length=16, verbose_name='Телефон'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hobby',
            name='img',
            field=models.ImageField(upload_to='media/img/', verbose_name='Иконка'),
        ),
    ]
