# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-27 13:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Наименование')),
                ('period', models.CharField(max_length=32, verbose_name='Период обучения')),
                ('spec', models.CharField(blank=True, max_length=32, verbose_name='Специальность')),
                ('link', models.CharField(blank=True, max_length=64, verbose_name='Ссылка')),
            ],
        ),
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Наименование')),
                ('img', models.ImageField(upload_to='media/img/', verbose_name='Иконка')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Организация')),
                ('region', models.CharField(blank=True, max_length=32, verbose_name='Регион')),
                ('tax_id', models.PositiveIntegerField(default=111111, verbose_name='ИНН')),
                ('site', models.CharField(blank=True, max_length=64, verbose_name='Сайт')),
                ('flag', models.BooleanField(default=False, verbose_name='Флаг')),
                ('phone', models.CharField(blank=True, max_length=16, verbose_name='Телефон')),
                ('address', models.CharField(default='Москва', max_length=128, verbose_name='Адрес')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='ФИО')),
                ('birthdate', models.DateField(verbose_name='Дата рождения')),
                ('text', models.TextField(verbose_name='Текст')),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=128, verbose_name='Должность')),
                ('duties', models.TextField(verbose_name='Обязаности')),
                ('period', models.CharField(max_length=32, verbose_name='Период работы работы')),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Organization', verbose_name='Организация')),
            ],
        ),
    ]
