# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='level',
            field=models.CharField(choices=[('Среднее образование', 'Среднее образование'), ('Неоконченное высшее образование', 'Неоконченное высшее образование')], max_length=255),
        ),
    ]
