# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-14 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0007_aboutdescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutdescription',
            name='post_date',
            field=models.DateField(auto_now=True),
        ),
    ]
