# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-19 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0011_auto_20161218_1539'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='location',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='name',
            new_name='short_name',
        ),
        migrations.AddField(
            model_name='company',
            name='full_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='phone',
            field=models.CharField(max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
