# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-19 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0012_auto_20161219_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='full_name',
            field=models.CharField(blank=True, default=models.CharField(max_length=255), max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
