# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-08 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spigen', '0002_auto_20170207_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='link',
            field=models.CharField(max_length=128, unique=True, verbose_name='Ссылка'),
        ),
    ]
