# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-08 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spigen', '0003_auto_20170208_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='preview',
            field=models.ImageField(blank=True, upload_to='media/pics/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(upload_to='media/pics/', verbose_name='Изображение'),
        ),
    ]
